### ISSUE TITLE
translate @tparam

### ISSUE THREAD

**Issue by patriknw** [lightbend/genjavadoc#65]
@tparam becomes an error in javadoc (JDK 8)

**Comment by manuzhang** [comment]
Any plan to support this ?

**Comment by ktoso** [comment]
Feel free to submit a PR if you want this feature

**Comment by manuzhang** [comment]
@ktoso PR at https://github.com/typesafehub/genjavadoc/pull/110

**Comment by ktoso** [comment]
Great, thanks :)

—
Konrad `kto.so` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 9 August 2017 at 22:25:47, Manu Zhang (notifications@github.com) wrote:

@ktoso <https://github.com/ktoso> PR at #110
<https://github.com/typesafehub/genjavadoc/pull/110>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/typesafehub/genjavadoc/issues/65#issuecomment-321254363>,
or mute the thread

**Comment by ktoso** [comment]
This was done
